spring:
  application:
    name: test
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8000