spring:
  application:
    name: test
  datasource:
    password: ${PASSWORD}
    username: ${USERNAME}
    url: ${JDBC_URL}
    name: rewards

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8000
